set encoding=utf-8 " エンコード
set fileencoding=utf-8 " ファイルエンコード
set noswapfile " .swapファイルを作らない
set nowritebackup " バックアップファイルを作らない
set nobackup " バックアップをしない
set number " 行番号を表示
set ruler " 右下に表示される行・列の番号を表示する
set cursorline " カーソルライン表示
set ignorecase " 小文字の検索でも大文字も見つかるようにする
set smartcase " ただし大文字も含めた検索の場合はその通りに検索する
set incsearch " インクリメンタルサーチを行う
set hlsearch " 検索結果をハイライト表示
set history=10000 " コマンド、検索パターンを10000個まで履歴に残す
set mouse=a " マウスモード有効
set showcmd " コマンドを画面最下部に表示する
set ttymouse=xterm2 " xtermとscreen対応
set expandtab " タブをスペースに置き換える
set tabstop=4 " タブを画面で表示する際の幅
set shiftwidth=4 " インデント時のスペースの数
set completeopt=menuone " 補完時にプレビューウィンドウが開かないようにする、分割時にガチャガチャ動くのを防ぐ
set backspace=indent,eol,start " バックスペースの動きを自然に
set clipboard+=unnamed " 無名レジスタに入るデータを＊レジスタにもいれる
